### PR TITLE
MAINT: Ensure sdist works

### PR DESCRIPTION
**Pull request by larsoner**
According to https://github.com/conda-forge/staged-recipes/pull/18752 and my local testing, this test should work but fails currently with:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-9_2zenck/setup.py", line 16, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Once I see CIs come back red (true TDD!), I'll try adding a MANIFEST.in that should fix this.

### CODE REVIEW

**Comment by larsoner** [comment]
@jackz314 please approve the workflows when you get a chance so I can continue!

**Comment by larsoner** [comment]
@jackz314 one option to make maintenance easier would be to add me as a maintainer or admin of the project, too. I might not be able to review all PRs, but I can try to help when I see things pop up.

If not, then this will require approval for each push. But once I have a PR merged it won't require approval anymore at least!

**Comment by jackz314** [comment]
> 

Just added you as a maintainer, thank you!

**Comment by larsoner** [comment]
I'm not 100% sure if we want `pymatreader` as a dependency, but it seems worthwhile to add since modern MATLAB writes out HDF5 files that scipy.io.loadmat can't read.

**Comment by larsoner** [comment]
I realized that pymatreader is only needed at the MNE-Python end to read files so I removed it from `requirements.txt`. I'll merge this once green and cut a release...

**Comment by sappelhoff** [comment]
nice, thanks @larsoner and @jackz314 ... this will be good for mne-bids as well.

**Pull request merged**
